DROP VIEW IF EXISTS pzh_refined;
CREATE VIEW pzh_refined AS
SELECT
  pzh_full.pzh_tr_id AS tr_id,
  pzh_full.pzh_tr_student_index AS student_index,
  pzh_full.pzh_tr_student_name AS student_name,
  pzh_full.pzh_preamble_subj_code AS subj_code,
  pzh_full.pzh_preamble_subj_name AS subj_name,
  pzh_full.pzh_preamble_subj_tutor AS subj_tutor,
  pzh_full.pzh_tr_subj_grade AS subj_grade,
  pzh_full.pzh_tr_subj_grade_final AS subj_grade_final,
  pzh_full.pzh_tr_subj_grade_project AS subj_grade_project,
  pzh_full.pzh_tr_subj_grade_lecture AS subj_grade_lecture,
  pzh_full.pzh_tr_subj_grade_class AS subj_grade_class,
  pzh_full.pzh_tr_subj_grade_p AS subj_grade_p,
  pzh_full.pzh_tr_subj_grade_n AS subj_grade_n,
  pzh_full.pzh_tr_edited_by AS tr_edited_by,
  pzh_full.pzh_tr_edited_datetime AS tr_edited_datetime,
  pzh_full.pzh_tr_edited_date AS tr_edited_date,
  pzh_full.pzh_report_source AS report_source,
  pzh_full.pzh_report_datetime AS report_open_datetime,
  pzh_full.pzh_preamble_title AS preamble_title,
  pzh_full.pzh_preamble_sheet_id AS sheet_id,
  pzh_full.pzh_preamble_semester_code AS semester_code,
  pzh_full.pzh_preamble_sheet_serie AS sheet_serie,
  pzh_full.pzh_preamble_sheet_number AS sheet_number,
  pzh_full.pzh_preamble_sheet_state AS sheet_state,
  pzh_full.pzh_preamble_subj_department AS subj_department,
  pzh_full.pzh_preamble_subj_grade_type AS subj_grade_type,
  pzh_full.pzh_preamble_return_date AS return_date,
  pzh_full.pzh_preamble_approved_by AS approved_by,
  pzh_full.pzh_preamble_modified_datetime AS modified_datetime,
  pzh_full.pzh_preamble_modified_date AS modified_date,
  pzh_full.pzh_preamble_return_deadline AS return_deadline
FROM pzh_full;
