DROP VIEW IF EXISTS pzhko_tr_usos_allstudents;
CREATE VIEW pzhko_tr_usos_allstudents AS
SELECT
  pzh_refined.tr_id AS pzh_tr_id,
  pzh_refined.student_index AS pzh_student_index,
  pzh_refined.student_name AS pzh_student_name,
  pzh_refined.subj_code AS pzh_subj_code,
  pzh_refined.subj_name AS pzh_subj_name,
  pzh_refined.subj_tutor AS pzh_subj_tutor,
  pzh_refined.subj_grade AS pzh_subj_grade,
  pzh_refined.subj_grade_final AS pzh_subj_grade_final,
  pzh_refined.subj_grade_project AS pzh_subj_grade_project,
  pzh_refined.subj_grade_class AS pzh_subj_grade_class,
  pzh_refined.subj_grade_p AS pzh_subj_grade_p,
  pzh_refined.subj_grade_n AS pzh_subj_grade_n,
  pzh_refined.tr_edited_by AS pzh_tr_edited_by,
  pzh_refined.tr_edited_date AS pzh_tr_edited_date,
  pzh_refined.report_source AS pzh_report_source,
  pzh_refined.sheet_id AS pzh_sheet_id,
  pzh_refined.semester_code AS pzh_semester_code,
  pzh_refined.sheet_state AS pzh_sheet_state,
  pzh_refined.subj_department AS pzh_subj_department,
  pzh_refined.subj_grade_type AS pzh_subj_grade_type,
  pzh_refined.approved_by AS pzh_approved_by,
  pzh_refined.modified_date AS pzh_modified_date,
  ko_tr_usos_allstudents.ko_tr_id AS ko_tr_id,
  ko_tr_usos_allstudents.ko_subj_code AS ko_subj_code,
  ko_tr_usos_allstudents.ko_subj_name AS ko_subj_name,
  ko_tr_usos_allstudents.ko_student_index AS ko_student_index,
  ko_tr_usos_allstudents.ko_student_name AS ko_student_name,
  ko_tr_usos_allstudents.ko_subj_grade AS ko_subj_grade,
  ko_tr_usos_allstudents.ko_subj_grade_date AS ko_subj_grade_date,
  ko_tr_usos_allstudents.ko_university AS ko_university,
  ko_tr_usos_allstudents.ko_faculty AS ko_faculty,
  ko_tr_usos_allstudents.ko_studies_modetier AS ko_studies_modetier,
  ko_tr_usos_allstudents.ko_studies_field AS ko_studies_field,
  ko_tr_usos_allstudents.ko_studies_specialty AS ko_studies_specialty,
  ko_tr_usos_allstudents.ko_studies_program_code AS ko_studies_program_code,
  ko_tr_usos_allstudents.ko_semester_code AS ko_semester_code,
  ko_tr_usos_allstudents.ko_semester_start_date AS ko_semester_start_date,
  ko_tr_usos_allstudents.ko_semester_end_date AS ko_semester_end_date,
  ko_tr_usos_allstudents.ko_semester_number AS ko_semester_number,
  ko_tr_usos_allstudents.ko_subj_tutor AS ko_subj_tutor,
  ko_tr_usos_allstudents.ko_subj_hours_w AS ko_subj_hours_w,
  ko_tr_usos_allstudents.ko_subj_hours_c AS ko_subj_hours_c,
  ko_tr_usos_allstudents.ko_subj_hours_l AS ko_subj_hours_l,
  ko_tr_usos_allstudents.ko_subj_hours_p AS ko_subj_hours_p,
  ko_tr_usos_allstudents.ko_subj_hours_s AS ko_subj_hours_s,
  ko_tr_usos_allstudents.ko_subj_credit_kind AS ko_subj_credit_kind,
  ko_tr_usos_allstudents.ko_subj_ects AS ko_subj_ects,
  ko_tr_usos_allstudents.ko_ects_mandatory AS ko_ects_mandatory,
  ko_tr_usos_allstudents.ko_ects_other AS ko_ects_other,
  ko_tr_usos_allstudents.ko_ects_total AS ko_ects_total,
  ko_tr_usos_allstudents.ko_ects_attained AS ko_ects_attained,
  ko_tr_usos_allstudents.ko_title AS ko_title,
  ko_tr_usos_allstudents.ko_report_source AS ko_report_source,
  ko_tr_usos_allstudents.ko_report_open_datetime AS ko_report_open_datetime,
  ko_tr_usos_allstudents.ko_report_sheets_parsed AS ko_report_sheets_parsed,
  ko_tr_usos_allstudents.ko_page_number AS ko_page_number,
  ko_tr_usos_allstudents.ko_sheet_first_page AS ko_sheet_first_page,
  ko_tr_usos_allstudents.usos_subj_code AS usos_subj_code,
  ko_tr_usos_allstudents.usos_person_id AS usos_person_id,
  ko_tr_usos_allstudents.usos_last_name AS usos_last_name,
  ko_tr_usos_allstudents.usos_first_name AS usos_first_name,
  ko_tr_usos_allstudents.usos_second_name AS usos_second_name,
  ko_tr_usos_allstudents.usos_student_index AS usos_student_index,
  ko_tr_usos_allstudents.usos_studies_program_code AS usos_studies_program_code,
  ko_tr_usos_allstudents.usos_progs_id AS usos_progs_id,
  ko_tr_usos_allstudents.usos_admission_date AS usos_admission_date,
  ko_tr_usos_allstudents.usos_discontinuation_date AS usos_discontinuation_date,
  ko_tr_usos_allstudents.usos_dissertation_date AS usos_dissertation_date,
  ko_tr_usos_allstudents.usos_studies_tier AS usos_studies_tier,
  ko_tr_usos_allstudents.usos_studies_mode AS usos_studies_mode,
  ko_tr_usos_allstudents.usos_studies_program_description AS usos_studies_program_description,
  ko_tr_usos_allstudents.usos_progs_ids_per_ko_tr AS usos_progs_ids_per_ko_tr,
  ko_tr_usos_allstudents.ko_semester_code_le_max_cdyd AS ko_semester_code_le_max_cdyd,
  ko_tr_usos_allstudents.ko_semester_start_date_ge_admission_date AS ko_semester_start_date_ge_admission_date,
  ko_tr_usos_allstudents.ko_semester_end_date_le_discontinuation_or_dissertation_date AS ko_semester_end_date_le_discontinuation_or_dissertation_date
FROM pzh_refined
LEFT JOIN ko_tr_usos_allstudents ON (
  pzh_refined.student_index = ko_tr_usos_allstudents.ko_student_index AND
  pzh_refined.subj_code = ko_tr_usos_allstudents.ko_subj_code AND
  pzh_refined.semester_code = ko_tr_usos_allstudents.ko_semester_code
);
