version: '3.5'
services:
  oracle-db:
    image: oracle/database:11.2.0.2-xe
    env_file:
      - "./docker-compose.env"
    ports:
      - "${VEETOU_ORA_SQL_PORT:-1521}:1521"
      - "${VEETOU_ORA_APEX_PORT:-8080}:8080"
      - "${VEETOU_ORA_EM_PORT:-5500}:5500"
    volumes:
      - ./share/oracle/docker/scripts/xe/setup:/u01/app/oracle/scripts/setup
      - ./share/oracle/docker/scripts/xe/startup:/u01/app/oracle/scripts/startup
    shm_size: '2gb'
