#!/bin/sh

USR="${ORACLE_VEETOU_USER:-VEETOU}"
PWD="${ORACLE_VEETOU_PWD:-${ORACLE_PWD:-`openssl rand -base64 8`1}}"

echo "ORACLE PASSWORD FOR $USR: $PWD";

sqlplus "sys/${ORACLE_PWD}@//localhost/XE" as sysdba <<!


-- CREATE USER
CREATE USER "${USR}" IDENTIFIED BY "${PWD}" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" ;

-- QUOTAS
ALTER USER "${USR}" QUOTA UNLIMITED ON "USERS" ;

-- ROLES
GRANT "CONNECT" TO "${USR}" ;
GRANT "RESOURCE" TO "${USR}" ;
ALTER USER "${USR}" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT ALTER SESSION TO "${USR}";
GRANT CREATE DATABASE LINK TO "${USR}";
GRANT CREATE PROCEDURE TO "${USR}";
GRANT CREATE SEQUENCE TO "${USR}";
GRANT CREATE SESSION TO "${USR}";
GRANT CREATE SYNONYM TO "${USR}";
GRANT CREATE TABLE TO "${USR}";
GRANT CREATE TRIGGER TO "${USR}";
GRANT CREATE VIEW TO "${USR}";
GRANT UNLIMITED TABLESPACE TO "${USR}";

EXIT
!
