CREATE MATERIALIZED VIEW LOG ON v2u_ko_footers
    WITH OBJECT ID
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_headers
    WITH OBJECT ID
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_jobs
    WITH OBJECT ID
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_pages
    WITH OBJECT ID
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_preambles
    WITH OBJECT ID
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_reports
    WITH OBJECT ID
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_sheets
    WITH OBJECT ID
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_tbodies
    WITH OBJECT ID
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_trs
    WITH OBJECT ID
    INCLUDING NEW VALUES;

-- vim: set ft=sql ts=4 sw=4 et:
