CREATE OR REPLACE TYPE V2u_Ko_Ids_t IS TABLE OF NUMBER(38);
/
CREATE OR REPLACE TYPE V2u_Integers_t IS TABLE OF NUMBER(38);
/
CREATE OR REPLACE TYPE V2u_Subj_Grades_t IS TABLE OF VARCHAR2(10);
/
CREATE OR REPLACE TYPE V2u_Subj_Codes_t IS TABLE OF VARCHAR2(32);
/
CREATE OR REPLACE TYPE V2u_Subj_Grades20_t IS VARRAY(20) OF VARCHAR2(10);
/
CREATE OR REPLACE TYPE V2u_Subj_Codes20_t IS VARRAY(20) OF VARCHAR2(32);

-- vim: set ft=sql ts=4 sw=4 et:
