CREATE OR REPLACE TYPE V2u_Ko_Ids_t IS TABLE OF NUMBER(38);
/
CREATE OR REPLACE TYPE V2u_Subj_Grades_t IS TABLE OF VARCHAR(10);
/
CREATE OR REPLACE TYPE V2u_Grade_Scale_t IS VARRAY(20) OF VARCHAR(10);

-- vim: set ft=sql ts=4 sw=4 et:
