@@distinct.tps;
@@university.tps;
@@faculty.tps;
@@semester.tps;
--
@@specialty_map_b.tps;
@@specialty_map.tps;
--
@@subject_map_b.tps;
@@subject_map.tps;
--
@@classes_map_b.tps;
@@classes_map.tps;
--
@@semester_pattern.tps;
@@specialty_pattern.tps;
@@subject_pattern.tps;
@@classes_pattern.tps;
--
@@specialty_map_pattern.tps;
@@subject_map_pattern.tps;
@@classes_map_pattern.tps;
--
-- vim: set ft=sql ts=4 sw=4 et:
