#!/bin/sh

USR="${ORACLE_VEETOU_USER:-VEETOU}"
PWD="${ORACLE_VEETOU_PWD:-${ORACLE_PWD:-`openssl rand -base64 8`1}}"

echo "ORACLE PASSWORD FOR $USR: $PWD";

sqlplus / as sysdba <<!
ALTER SESSION SET CONTAINER="${ORACLE_PDB:-ORCLPDB1}" ;

-- CREATE USER
CREATE USER "${USR}" IDENTIFIED BY "${PWD}" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" ;

-- QUOTAS
ALTER USER "${USR}" QUOTA UNLIMITED ON "USERS" ;

-- ROLES
GRANT "CONNECT" TO "${USR}" ;
GRANT "PDB_DBA" TO "${USR}" ;
GRANT "RESOURCE" TO "${USR}" ;
ALTER USER "${USR}" DEFAULT ROLE "CONNECT","PDB_DBA","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "${USR}";

EXIT
!
