--@@dx_studenci.sql;
--@@dx_atrybuty_przedmiotow.sql;
--@@dx_przedmioty.sql;
--@@dx_przedmioty_obce.sql;
--@@dx_przedmioty_cykli.sql;
@@dx_punkty_przedmiotow.sql;
--@@dx_zajecia_cykli.sql;
--@@dx_zajecia_prz_obcych.sql;
--@@dx_programy.sql;
--@@dx_programy_osob.sql;
--@@dx_decyzje.sql;
--@@dx_etapy.sql;
--@@dx_etapy_programow.sql;
--@@dx_etapy_kierunkow.sql;
--@@dx_etapy_osob.sql;
--@@dx_zaliczenia_przedmiotow.sql;
--@@dx_zal_przedm_prgos.sql;
--@@dx_oceny.sql;
--@@dx_terminy_protokolow.sql;
--@@dx_protokoly.sql;

-- vim: set ft=sql ts=4 sw=4 et:
