#!/bin/sh

sqlplus / as sysdba <<!
ALTER SESSION SET CONTAINER="${ORACLE_VEETOU_PDB:-${ORACLE_PDB:-ORCLPDB1}}" ;

-- CREATE USER
CREATE USER "${ORACLE_VEETOU_USER:-VEETOU}" IDENTIFIED BY "${ORACLE_VEETOU_PWD:-${ORACLE_PWD:-Ve3T0UpWd}}" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" ;

-- QUOTAS
ALTER USER "VEETOU" QUOTA UNLIMITED ON "USERS" ;

-- ROLES
GRANT "CONNECT" TO "VEETOU" ;
GRANT "PDB_DBA" TO "VEETOU" ;
GRANT "RESOURCE" TO "VEETOU" ;
ALTER USER "VEETOU" DEFAULT ROLE "CONNECT","PDB_DBA","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO "VEETOU";

EXIT
!
