--@@xr_studenci.ddl;
--@@xr_przedmioty.ddl;
--@@xr_przedmioty_obce.ddl;
--@@xr_atrybuty_przedmiotow.ddl;
--@@xr_przedmioty_cykli.ddl;
@@xr_punkty_przedmiotow.ddl;
--@@xr_zajecia_cykli.ddl;
--@@xr_zajecia_prz_obcych.ddl;
--@@xr_programy.ddl;
--@@xr_programy_osob.ddl;
--@@xr_decyzje.ddl;
--@@xr_etapy.ddl;
--@@xr_etapy_programow.ddl;
--@@xr_etapy_kierunkow.ddl;
--@@xr_etapy_osob.ddl;
--@@xr_zaliczenia_przedmiotow.ddl;
--@@xr_zal_przedm_prgos.ddl;
--@@xr_oceny.ddl;
--@@xr_terminy_protokolow.ddl;
--@@xr_protokoly.ddl;

-- vim: set ft=sql ts=4 sw=4 et:
