CREATE MATERIALIZED VIEW LOG ON v2u_ko_footers
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_headers
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_jobs
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_pages
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_preambles
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_reports
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_sheets
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_tbodies
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_trs
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON v2u_ko_page_footer
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_page_header
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_page_preamble
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_page_tbody
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_report_sheets
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_sheet_pages
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_tbody_trs
    WITH ROWID, PRIMARY KEY
    INCLUDING NEW VALUES;

-- vim: set ft=sql ts=4 sw=4 et:
