@@ko_jobs_ov.ddl;
@@ko_reports_ov.ddl;
@@ko_sheets_ov.ddl;
@@ko_pages_ov.ddl;
@@ko_headers_ov.ddl;
@@ko_preambles_ov.ddl;
@@ko_tbodies_ov.ddl;
@@ko_footers_ov.ddl;
@@ko_trs_ov.ddl;
@@semesters_ov.ddl;
@@subject_mappings_ov.ddl;
@@program_mappings_ov.ddl;
----
@@ko_x_trs.sql;
@@ko_x_sheets.sql;
--@@ko_sheet_infos.sql;
@@ko_subject_instances.sql;
--@@ko_specialties.sql;
--@@ko_specialty_instances.sql;
--@@ko_students.sql;
--@@ko_student_specialties.sql;
--@@ko_student_threads.sql;
--@@ko_threads.sql;
--@@ko_mapped_subjects.sql;
--@@ko_mapped_programs.sql;
--@@ko_ambiguous_subjects.sql;
--@@ko_ambiguous_programs.sql;
--@@ko_unmapped_subjects.sql;
--@@ko_unmapped_programs.sql;
--@@ko_subject_grades.sql;

-- vim: set ft=sql ts=4 sw=4 et:
