#!/bin/sh

set -e

TOPDIR="$(dirname $0)/.."

numpages() { pdfinfo "$1" | awk '/^Pages:/ {print $2}'; }
pagetext() { pdftotext -f "$2" -l "$2" -layout "$1" -; }

if [ $# -lt 1 ]; then
  echo "error: page processor not specified" >&2;
  exit 1;
fi
PROC="${TOPDIR}/pageproc/$1";

shift
if [ $# -lt 1 ]; then
  echo "error: input file name required" >&2;
  exit 1;
fi

PDF="$1";
shift;

NP=$(numpages "$PDF");
if [ "$NP" -ge 1 ]; then
  pagetext "$PDF" 1 | "$PROC" -f "$PDF" -p 1 -c
  for N in $(seq 2 "$NP"); do
    pagetext "$PDF" "$N" | "$PROC" -f "$PDF" -p "$N"
  done
fi
