CREATE MATERIALIZED VIEW LOG ON v2u_ko_page_footer
    WITH PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_page_header
    WITH PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_page_preamble
    WITH PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_page_tbody
    WITH PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_report_sheets
    WITH PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_sheet_pages
    WITH PRIMARY KEY
    INCLUDING NEW VALUES;
CREATE MATERIALIZED VIEW LOG ON v2u_ko_tbody_trs
    WITH PRIMARY KEY
    INCLUDING NEW VALUES;

-- vim: set ft=sql ts=4 sw=4 et:
